name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: "WyriHaximus/github-action-get-previous-tag@v1"
        id: version

      - uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - run: mvn package
