name: master

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Maven
      run: mvn install -Dgpg.skip=true -B -ntp

    - uses: actions-ecosystem/action-get-latest-tag@v1
      id: previoustag

    - name: Next SemVers
      uses: WyriHaximus/github-action-next-semvers@v1.0
      id: semvers
      with:
        version: ${{ steps.previoustag.outputs.tag }}

    - name: Create an Tag
      run: |
        echo ${{ steps.semvers.outputs.patch }}
#       uses: simpleactions/create-tag@v1.0.0
#       with:
#         tag: ${{ steps.semvers.outputs.patch }}
