name: Publish

on:
  pull_request:
    types: [closed]
    branches: master

jobs:
  build:
    if: ${{ github.event.pull_request.merged == true }} && ${{ github.event.label.name == 'bug' }}
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2.3.2

    - name: Increment Step Patch
      id: increment-semver-patch
      uses: Benbentwo/increment-semver@master
      if: github.
      with:
        version-level: '-p'

    - name: Get the output version
      run: |
        echo "The new patch version was ${{ steps.increment-semver-patch.outputs.version }}"
