name: Publish

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.2

    - name: Get next version
      id: next-version
      uses: technote-space/get-next-version-action@v1

    - name: echo calculated version
      run: |
        echo "version: ${{ steps.next-version.outputs.current }}"
        echo "version: ${{ steps.next-version.outputs.next }}"
