name: Publish

on:
  pull_request:
    types: [closed]
    branches: master

jobs:
  generate:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2.3.2

    - name: 'Get Previous tag'
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@master"
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    - name: 'Get next minor version'
      id: semvers
      uses: "WyriHaximus/github-action-next-semvers@v1"
      with:
        version: ${{ steps.previoustag.outputs.tag }}

  bug:
    if: ${{ github.event.label.name == 'bug' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.2

  enchantment:
    if: ${{ github.event.label.name == 'enchantment' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.2

  major:
    if: ${{ github.event.label.name == 'major' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.2
