name: Publish

on:
  push:
    branches: master

jobs:
  build:
    if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2.3.2

    - name: calculate next version
      id: version
      uses: patrickjahns/version-drafter-action@v1.1.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: echo calculated version
      run: |
        echo "version: ${{ steps.version.outputs.next-version }}"
