name: Publish

on:
  pull_request:
    types: [closed]
    branches: master

jobs:
  generate:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2.3.2

    - name: Bug
      if: ${{ !contains(github.event.pull_request.labels.*.names, 'bug') }}
      id: bug
      uses: PssbleTrngle/VersionManagment@v1.0.8
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        fallback: '0.0.1'
        default-fragment: bug

    - name: Minor
      if: ${{ !contains(github.event.pull_request.labels.*.names, 'minor') }}
      id: minor
      uses: PssbleTrngle/VersionManagment@v1.0.8
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        fallback: '0.0.1'
        default-fragment: minor

    - name: Major
      if: ${{ !contains(github.event.pull_request.labels.*.names, 'major') }}
      id: major
      uses: PssbleTrngle/VersionManagment@v1.0.8
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        fallback: '0.0.1'
        default-fragment: major

    - name: echo
      run: |
        echo Test: ${{steps.nextversion.outputs.next}}
        echo Test: ${{steps.nextversion.outputs.next}}
        echo Test: ${{steps.nextversion.outputs.next}}
