name: Publish

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1.4.1
      with:
        java-version: 1.8

    - name: Build with Maven
      run: mvn -B package -ntp

    - name: Increment Step Patch
      id: increment-semver-patch
      uses: Benbentwo/increment-semver@master
      with:
        version-level: '-p'

    - name: Echo the next version
      run: |
        echo ${{ steps.increment-semver-patch.outputs.version }}
