name: Publish

on:
  push:
    branches: master

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2.3.2

    - name: 'Get previous tag'
      id: previoustag
      run: |
        echo "::set-output name=previousversion::$(git for-each-ref refs/tags/ --count=1 --sort=-version:refname --format='%(refname:short)')"

    - name: 'Get next minor version'
      id: semvers
      uses: "WyriHaximus/github-action-next-semvers@v1"
      with:
        version: ${{ steps.previoustag.outputs.previousversion }}

    - name: 'Echo the next version'
      run: |
        echo ${{ steps.semvers.outputs.patch }}
        echo ${{ steps.semvers.outputs.minor }}
        echo ${{ steps.semvers.outputs.major }}
