name: Publish

on:
  push:
    branches: master

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2.3.2

    - name: Version Bump
      uses: opspresso/action-version@v0.2.5
